#line 2 "lexer.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 68
#define YY_END_OF_BUFFER 69
static yyconst short int yy_acclist[353] =
    {   0,
       69,   67,   68,   66,   67,   68,   66,   68,   67,   68,
       67,   68,   67,   68,   67,   68,   67,   68,   52,   67,
       68,   52,   67,   68,   67,   68,   67,   68,   67,   68,
       51,   67,   68,   51,   67,   68,   51,   67,   68,   51,
       67,   68,   51,   67,   68,   51,   67,   68,   51,   67,
       68,   51,   67,   68,   51,   67,   68,   51,   67,   68,
       51,   67,   68,   51,   67,   68,   51,   67,   68,   51,
       67,   68,   51,   67,   68,   51,   67,   68,   51,   67,
       68,   51,   67,   68,   51,   67,   68,   51,   67,   68,
       51,   67,   68,   65,   60,    9,   61,   52,   54,   52,

       64,   52,   50,   48,   49,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   23,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       65,    4,   58,   58,   63,   60,    8,   60,   61,   62,
       61,   52,   54,   59,   53,   51,   51,   51,   10,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   32,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   57,   55,   57,   60,   62,   63,   60,   61,

       61,   59,   53,   51,   51,   47,   51,   51,   51,   13,
       51,   14,   51,   51,   51,   51,   51,   19,   51,   51,
       51,   51,   51,   51,   26,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       43,   51,   51,   51,   55,   56,   60,   61,   46,   51,
       51,   51,   51,   15,   51,   51,   51,   51,   51,   21,
       51,   22,   51,   24,   51,   51,   51,   51,   30,   51,
       51,   51,   51,   51,   36,   51,   51,   51,   51,   51,
       41,   51,   51,   44,   51,   51,    5,   29,   51,   51,
       51,   51,   51,   18,   51,   51,   51,   27,   51,   28,

       51,   31,   51,   33,   51,   51,   51,   37,   51,   38,
       51,   39,   51,   51,   51,   51,    1,   51,   12,   51,
       16,   51,   17,   51,   51,   51,   51,   51,   40,   51,
       51,   45,   51,    6,    2,   51,   51,   51,   34,   51,
       35,   51,   42,   51,   11,   51,   20,   51,   25,   51,
        3,    7
    } ;

static yyconst short int yy_accept[315] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   11,   13,   15,
       17,   19,   22,   25,   27,   29,   31,   34,   37,   40,
       43,   46,   49,   52,   55,   58,   61,   64,   67,   70,
       73,   76,   79,   82,   85,   88,   91,   94,   94,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   96,   97,
       97,   98,  100,  101,  102,  102,  103,  103,  104,  105,
      106,  107,  108,  109,  110,  111,  112,  113,  114,  115,
      116,  117,  118,  119,  120,  121,  122,  124,  125,  126,
      127,  128,  129,  130,  131,  132,  133,  134,  135,  136,
      137,  138,  139,  140,  141,  142,  142,  143,  143,  143,

      143,  144,  144,  145,  145,  145,  146,  146,  147,  147,
      148,  150,  151,  151,  152,  154,  154,  155,  156,  157,
      158,  159,  161,  162,  163,  164,  165,  166,  167,  168,
      169,  170,  171,  172,  173,  174,  175,  176,  177,  178,
      179,  181,  182,  183,  184,  185,  186,  187,  188,  189,
      190,  191,  192,  193,  193,  193,  193,  193,  193,  194,
      196,  196,  196,  196,  197,  199,  199,  201,  201,  202,
      203,  204,  205,  206,  208,  209,  210,  212,  214,  215,
      216,  217,  218,  220,  221,  222,  223,  224,  225,  227,
      228,  229,  230,  231,  232,  233,  234,  235,  236,  237,

      238,  239,  240,  241,  243,  244,  245,  245,  245,  245,
      245,  245,  245,  246,  246,  247,  247,  247,  249,  251,
      252,  253,  254,  256,  257,  258,  259,  260,  262,  264,
      266,  267,  268,  269,  271,  272,  273,  274,  275,  277,
      278,  279,  280,  281,  283,  284,  286,  287,  287,  288,
      288,  288,  288,  288,  290,  291,  292,  293,  294,  296,
      297,  298,  300,  302,  304,  306,  307,  308,  310,  312,
      314,  315,  316,  317,  317,  317,  318,  318,  318,  319,
      321,  323,  325,  326,  327,  328,  329,  331,  332,  334,
      334,  334,  335,  335,  336,  337,  338,  339,  341,  343,

      345,  345,  345,  347,  349,  351,  351,  351,  351,  351,
      352,  352,  353,  353
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    7,    1,    1,    8,    1,
        1,    9,   10,    1,   10,   11,   12,   13,   14,   14,
       14,   14,   14,   14,   14,   15,   15,   16,    1,   17,
        1,   18,    1,    1,   19,   20,   20,   21,   22,   23,
       24,   24,   24,   24,   24,   25,   24,   24,   26,   24,
       24,   27,   28,   29,   30,   24,   24,   31,   24,   24,
        1,   32,    1,    1,   33,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   43,   24,   44,   45,   46,
       47,   48,   49,   50,   51,   52,   53,   54,   55,   56,
       57,   24,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[58] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    4,    4,    4,    1,    1,    1,    4,    4,
        4,    4,    4,    5,    5,    5,    5,    5,    5,    5,
        5,    1,    5,    4,    4,    4,    4,    4,    4,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5
    } ;

static yyconst short int yy_base[329] =
    {   0,
        0,    0,  511,  512,  512,  512,   53,   57,  478,   47,
       54,   95,   51,  493,  491,  489,    0,  487,  470,  477,
       21,  456,   34,   31,   28,   35,  456,  454,  453,  465,
       40,   49,   59,  441,  451,  449,   44,   83,  512,   86,
      121,  127,  458,  452,  443,  484,   90,  157,  512,  488,
      189,  130,    0,  512,  139,  512,    0,  512,  512,  512,
        0,  465,  446,  458,  430,  434,  438,  433,  449,  436,
      442,  427,  426,  442,  421,  429,   42,  429,  437,  421,
      420,  433,  418,  427,  434,  418,  419,  415,  422,  415,
       70,  420,  420,  408,   87,  182,  512,  421,  412,  423,

      512,  448,  447,  114,  446,  512,  178,  512,  450,  512,
      221,  512,  203,  512,  512,  130,  206,  137,  424,  413,
      428,    0,  399,  404,  409,  396,   86,  411,  409,  398,
      404,  403,  406,  386,  400,  397,  383,  393,  396,  378,
        0,  381,  394,  377,  379,   60,  376,  389,  379,  383,
      387,  389,  372,  416,  372,  373,  380,  377,  512,  512,
      192,  408,  143,  224,  512,  238,  512,  162,  241,  512,
      512,  393,  378,    0,  371,  374,    0,    0,  359,  372,
      356,  364,    0,  359,  369,  353,  352,  353,    0,  358,
      347,  348,  365,  360,  350,  358,  343,  348,  357,  356,

      354,  344,  349,    0,  338,  345,  381,  382,  334,  331,
      380,  336,  512,  372,  512,  371,  184,  256,    0,  326,
      342,  342,    0,  319,  330,  335,  320,    0,    0,    0,
      332,  332,  331,    0,  311,  316,  320,  319,    0,  324,
      311,  321,  276,    0,  261,    0,  253,  295,  512,  263,
      293,  259,  260,    0,  240,  246,  239,  238,    0,  247,
      250,    0,    0,    0,    0,  239,  246,    0,    0,    0,
      239,  239,  227,  222,  254,  512,  273,  238,  188,    0,
        0,    0,  185,  194,  167,  177,    0,  172,    0,  163,
      220,  512,  204,  512,  135,  122,  128,    0,    0,    0,

      130,  154,    0,    0,    0,  147,  142,  128,  121,  512,
       93,  512,  512,  300,  305,  307,  312,  317,   86,  320,
      324,  327,  331,  336,  341,  346,  351,  356
    } ;

static yyconst short int yy_def[329] =
    {   0,
      313,    1,  313,  313,  313,  313,  314,  313,  315,  313,
      313,  313,   12,  313,  313,  313,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  314,  313,  314,
      313,  313,  313,  313,  313,  313,  317,  313,  313,  318,
      313,   12,   13,  313,  313,  313,  319,  313,  313,  313,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  314,  313,  313,  313,  313,  313,

      313,  313,  313,  313,  320,  313,  313,  313,  318,  313,
      313,  313,  313,  313,  313,  313,  313,  319,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  321,  313,  313,  313,  313,  313,  313,
      313,  322,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,

      316,  316,  316,  316,  316,  316,  321,  323,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  323,  313,  313,
      324,  313,  313,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  313,  324,  313,  313,  325,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  313,
      313,  313,  325,  313,  316,  316,  316,  316,  316,  316,

      313,  326,  316,  316,  316,  327,  326,  328,  327,  313,
      328,  313,    0,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313
    } ;

static yyconst short int yy_nxt[570] =
    {   0,
        4,    5,    6,    5,    7,    8,    4,    9,    4,    4,
       10,   11,   12,   13,   13,   14,   15,   16,   17,   17,
       17,   17,   18,   17,   17,   19,   17,   17,   20,   17,
       17,    4,    4,   21,   22,   23,   24,   25,   26,   17,
       17,   27,   17,   28,   29,   30,   31,   17,   17,   32,
       33,   34,   35,   36,   37,   17,   17,   39,   41,   48,
       48,   48,   49,   53,   53,   50,   65,   68,   71,   42,
       42,   42,   66,   73,   69,   81,   75,   72,   76,   93,
       70,  313,   84,   74,   40,   82,   85,   39,  134,  118,
       95,   39,   83,  135,   94,  312,   86,  103,   43,   87,

       44,  198,  104,  104,   45,   51,  313,   52,   52,   53,
       88,  149,  199,   89,   40,   54,   55,   40,   40,   56,
      150,  160,   41,  310,   56,   57,  161,  161,   96,   97,
      312,   54,   55,   42,   42,   42,  179,  180,   56,   42,
       42,   42,  117,  117,  117,  105,  308,   56,  116,  310,
       57,  117,  117,  117,  115,  164,  164,  164,  308,  115,
      313,  171,   43,  306,   44,  305,  171,  304,   45,   48,
       48,   48,  303,  115,  169,  169,  169,  106,  107,  108,
      171,  108,  115,   96,   97,  313,  154,  163,  155,  171,
      164,  164,  164,  106,  107,  108,  218,  218,  218,  213,

      108,  111,  111,  111,  214,  214,  294,  301,  300,  112,
      113,  114,  168,  114,  299,  169,  169,  169,  117,  117,
      117,  291,  292,  298,  302,  112,  113,  114,  170,  297,
      170,  296,  114,  111,  111,  111,  164,  164,  164,  295,
      294,  165,  166,  167,  170,  167,  108,  217,  108,  170,
      218,  218,  218,  169,  169,  169,  276,  165,  166,  167,
      252,  290,  108,  114,  167,  114,  289,  108,  218,  218,
      218,  277,  277,  277,  291,  292,  288,  287,  167,  114,
      167,  286,  285,  284,  114,  277,  277,  277,  283,  282,
      281,  280,  279,  278,  167,  276,  274,  249,  273,  167,

       38,   38,   38,   38,   38,   46,  272,   46,   46,   46,
       61,   61,  102,  271,  102,  102,  102,  109,  109,  109,
      109,  109,  162,  162,  207,  207,  207,  207,  207,  216,
      216,  248,  248,  248,  248,  248,  275,  275,  275,  275,
      275,  293,  293,  293,  293,  293,  307,  307,  307,  307,
      307,  309,  309,  309,  309,  309,  311,  311,  311,  311,
      311,  270,  269,  268,  267,  266,  265,  264,  263,  262,
      261,  260,  259,  258,  257,  256,  255,  254,  215,  213,
      253,  252,  251,  250,  249,  208,  247,  246,  245,  244,
      243,  242,  241,  240,  239,  238,  237,  236,  235,  234,

      233,  232,  231,  230,  229,  228,  227,  226,  225,  224,
      223,  222,  221,  220,  219,  215,  212,  211,  210,  209,
      208,  206,  205,  204,  203,  202,  201,  200,  197,  196,
      195,  194,  193,  192,  191,  190,  189,  188,  187,  186,
      185,  184,  183,  182,  181,  178,  177,  176,  175,  174,
      173,  172,  110,  159,  159,  159,  158,  157,  156,  153,
      152,  151,  148,  147,  146,  145,  144,  143,  142,  141,
      140,  139,  138,  137,  136,  133,  132,  131,  130,  129,
      128,  127,  126,  125,  124,  123,  122,  121,  120,  119,
      110,  101,  100,   99,   98,   92,   91,   90,   80,   79,

       78,   77,   67,   64,   63,   62,   60,   59,   58,   47,
      313,    3,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313
    } ;

static yyconst short int yy_chk[570] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    7,    8,   10,
       10,   10,   11,   13,   13,   11,   21,   23,   24,    8,
        8,    8,   21,   25,   23,   31,   26,   24,   26,   37,
       23,   13,   32,   25,    7,   31,   32,   38,   77,  319,
       40,   95,   31,   77,   37,  311,   33,   47,    8,   33,

        8,  146,   47,   47,    8,   12,   13,   12,   12,   12,
       33,   91,  146,   33,   38,   12,   12,   40,   95,   12,
       91,  104,   41,  309,   12,   12,  104,  104,   42,   42,
      308,   12,   12,   41,   41,   41,  127,  127,   12,   42,
       42,   42,  116,  116,  116,   47,  307,   12,   55,  306,
       12,   55,   55,   55,   52,  163,  163,  163,  302,   52,
       52,  118,   41,  301,   41,  297,  118,  296,   41,   48,
       48,   48,  295,   52,  168,  168,  168,   48,   48,   48,
      118,   48,   52,   96,   96,   52,   96,  107,   96,  118,
      107,  107,  107,   48,   48,   48,  217,  217,  217,  161,

       48,   51,   51,   51,  161,  161,  293,  290,  288,   51,
       51,   51,  113,   51,  286,  113,  113,  113,  117,  117,
      117,  291,  291,  285,  291,   51,   51,   51,  117,  284,
      117,  283,   51,  111,  111,  111,  164,  164,  164,  279,
      278,  111,  111,  111,  117,  111,  164,  166,  164,  117,
      166,  166,  166,  169,  169,  169,  275,  111,  111,  111,
      252,  274,  164,  169,  111,  169,  273,  164,  218,  218,
      218,  252,  252,  252,  277,  277,  272,  271,  218,  169,
      218,  267,  266,  261,  169,  277,  277,  277,  260,  258,
      257,  256,  255,  253,  218,  251,  250,  248,  247,  218,

      314,  314,  314,  314,  314,  315,  245,  315,  315,  315,
      316,  316,  317,  243,  317,  317,  317,  318,  318,  318,
      318,  318,  320,  320,  321,  321,  321,  321,  321,  322,
      322,  323,  323,  323,  323,  323,  324,  324,  324,  324,
      324,  325,  325,  325,  325,  325,  326,  326,  326,  326,
      326,  327,  327,  327,  327,  327,  328,  328,  328,  328,
      328,  242,  241,  240,  238,  237,  236,  235,  233,  232,
      231,  227,  226,  225,  224,  222,  221,  220,  216,  214,
      212,  211,  210,  209,  208,  207,  206,  205,  203,  202,
      201,  200,  199,  198,  197,  196,  195,  194,  193,  192,

      191,  190,  188,  187,  186,  185,  184,  182,  181,  180,
      179,  176,  175,  173,  172,  162,  158,  157,  156,  155,
      154,  153,  152,  151,  150,  149,  148,  147,  145,  144,
      143,  142,  140,  139,  138,  137,  136,  135,  134,  133,
      132,  131,  130,  129,  128,  126,  125,  124,  123,  121,
      120,  119,  109,  105,  103,  102,  100,   99,   98,   94,
       93,   92,   90,   89,   88,   87,   86,   85,   84,   83,
       82,   81,   80,   79,   78,   76,   75,   74,   73,   72,
       71,   70,   69,   68,   67,   66,   65,   64,   63,   62,
       50,   46,   45,   44,   43,   36,   35,   34,   30,   29,

       28,   27,   22,   20,   19,   18,   16,   15,   14,    9,
        3,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#define INITIAL 0
#line 2 "lexer.l"

/***************************************************************

  Copyright (C) DSTC Pty Ltd (ACN 052 372 577) 1997, 1998, 1999
  Unpublished work.  All Rights Reserved.

  The software contained on this media is the property of the
  DSTC Pty Ltd.  Use of this software is strictly in accordance
  with the license agreement in the accompanying LICENSE.HTML
  file.  If your distribution of this software does not contain
  a LICENSE.HTML file then you have no rights to use this
  software in any manner and should contact DSTC at the address
  below to determine an appropriate licensing arrangement.

     DSTC Pty Ltd
     Level 7, GP South
     Staff House Road
     University of Queensland
     St Lucia, 4072
     Australia
     Tel: +61 7 3365 4310
     Fax: +61 7 3365 4311
     Email: enquiries@dstc.edu.au

  This software is being provided "AS IS" without warranty of
  any kind.  In no event shall DSTC Pty Ltd be liable for
  damage of any kind arising out of or in connection with
  the use or performance of this software.


  Project:      Fnorb
  File:         $Source: /units/arch/src/Fnorb/src/RCS/lexer.l,v $
  Version:      @(#)$RCSfile: lexer.l,v $ $Revision: 1.7 $


  Description:	Flex lexer for OMG IDL.

****************************************************************/

#include <stdlib.h>
#include <errno.h>
#include "Python.h"

/* The lexer returns all semantic values as Python objects! */
#define YYSTYPE PyObject*

/* Convenience macro to return 'yytext' as a Python string object. */
#define PY_YYTEXT PyString_FromString(yytext)

#include "grammar.h"
#include "bisonmodule.h"

/* Function defined in 'grammar.y'. */
void yywarning(char*);

/* Forward declarations. */
/*PyObject* integer_literal(const char*, const int);*/
PyObject* floating_point_literal(const char*);

#line 708 "lexer.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 81 "lexer.l"


#line 862 "lexer.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 314 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 512 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 83 "lexer.l"
{
    /*
     * '#ident' directive.
     */
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 89 "lexer.l"
{
    /*
     * '#pragma' directive.
     *
     * e.g. "# pragma prefix "dstc.edu.au"
     */
    yylval = PY_YYTEXT;
    return PRAGMA;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 99 "lexer.l"
{
    /*
     * '#pragma' directive.
     *
     * e.g. "# 1 pragma prefix "dstc.edu.au"
     */
    yylval = PY_YYTEXT;
    return PRAGMA;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 109 "lexer.l"
{
    /*
     * Line/file directive.
     *
     * e.g. "# 1"
     */
    CALL_1("line_directive", PY_YYTEXT);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 118 "lexer.l"
{
    /*
     * Line/file directive.
     *
     * e.g. "# 1 filename.idl"
     */
    CALL_1("line_directive", PY_YYTEXT);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 127 "lexer.l"
{
    /*
     * '#line' directive.
     *
     * e.g. "# line 1"
     */
    CALL_1("line_directive", PY_YYTEXT);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 136 "lexer.l"
{
    /*
     * '#line' directive.
     *
     * e.g. "# line 1 "filename.idl"
     */
    CALL_1("line_directive", PY_YYTEXT);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 145 "lexer.l"
{
    /*
     * C++ style comments.
     */
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 151 "lexer.l"
{
    /*
     * C style comments.
     */
    while (1)
    {
	int c = input();
	if (c == '*')
	{
	    int next = input();
	    if (next == '/')
	    {
		break;
	    }
	    else
	    {
		unput(next);
	    }
	}
	else if (c == EOF)
	{
	    yywarning("End of file in comment");
	    break;
	}
    }
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 178 "lexer.l"
return IDL_ANY;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 179 "lexer.l"
return ATTRIBUTE;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 180 "lexer.l"
return BOOLEAN;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 181 "lexer.l"
return CASE;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 182 "lexer.l"
return CHAR;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 183 "lexer.l"
return CONST;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 184 "lexer.l"
return CONTEXT;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 185 "lexer.l"
return DEFAULT;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 186 "lexer.l"
return DOUBLE;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 187 "lexer.l"
return ENUM;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 188 "lexer.l"
return EXCEPTION;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 189 "lexer.l"
return FIXED;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 190 "lexer.l"
return FLOAT;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 191 "lexer.l"
return IN;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 192 "lexer.l"
return INOUT;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 193 "lexer.l"
return INTERFACE;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 194 "lexer.l"
return LONG;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 195 "lexer.l"
return MODULE;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 196 "lexer.l"
return NATIVE;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 197 "lexer.l"
return OBJECT;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 198 "lexer.l"
return OCTET;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 199 "lexer.l"
return ONEWAY;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 200 "lexer.l"
return OUT;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 201 "lexer.l"
return RAISES;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 202 "lexer.l"
return READONLY;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 203 "lexer.l"
return SEQUENCE;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 204 "lexer.l"
return SHORT;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 205 "lexer.l"
return STRING;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 206 "lexer.l"
return STRUCT;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 207 "lexer.l"
return SWITCH;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 208 "lexer.l"
return TYPEDEF;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 209 "lexer.l"
return UNION;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 210 "lexer.l"
return UNSIGNED;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 211 "lexer.l"
return VOID;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 212 "lexer.l"
return WCHAR;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 213 "lexer.l"
return WSTRING;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 215 "lexer.l"
return IDL_FALSE;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 216 "lexer.l"
return IDL_TRUE;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 218 "lexer.l"
return LEFT_SHIFT;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 219 "lexer.l"
return RIGHT_SHIFT;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 220 "lexer.l"
return SCOPE_DELIMITER;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 222 "lexer.l"
{
                            yylval = PY_YYTEXT;
    			    return IDENTIFIER;
		        }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 227 "lexer.l"
{
    /*                           
                           yylval = integer_literal(yytext, 10);
    */
                           yylval = PY_YYTEXT;
                           return INTEGER_LITERAL;
			}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 235 "lexer.l"
{
    /*
                            yylval = integer_literal(yytext + 2, 16);
    */
                            yylval = PY_YYTEXT;
                            return INTEGER_LITERAL;
                        }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 243 "lexer.l"
{
    /*
                            yylval = integer_literal(yytext + 1, 8);
    */
                            yylval = PY_YYTEXT;
                            return INTEGER_LITERAL;
			}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 251 "lexer.l"
{
			    yylval = PY_YYTEXT;
                            return CHARACTER_LITERAL;
			}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 256 "lexer.l"
{
			    yylval = PY_YYTEXT;
                            return CHARACTER_LITERAL;
			}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 261 "lexer.l"
{
			    yylval = PY_YYTEXT;
                            return CHARACTER_LITERAL;
			}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 266 "lexer.l"
{
                            yylval = PY_YYTEXT;
                            return CHARACTER_LITERAL;
			}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 271 "lexer.l"
{
                            yylval = floating_point_literal(yytext);
                            return FLOATING_PT_LITERAL;
			}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 276 "lexer.l"
{
                            yylval = floating_point_literal(yytext);
                            return FLOATING_PT_LITERAL;
			}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 281 "lexer.l"
{
                            yylval = floating_point_literal(yytext);
                            return FLOATING_PT_LITERAL;
			}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 286 "lexer.l"
{
                            yylval = PY_YYTEXT;
                            return FIXED_PT_LITERAL;
			}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 291 "lexer.l"
{
                            yylval = PY_YYTEXT;
                            return FIXED_PT_LITERAL;
			}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 296 "lexer.l"
{
                            yylval = PY_YYTEXT;
                            return FIXED_PT_LITERAL;
			}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 301 "lexer.l"
{
			    yylval = PY_YYTEXT;
	                    return STRING_LITERAL;
			}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 306 "lexer.l"
{
    			    /* Ignore whitespace. */
                        }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 310 "lexer.l"
{
                            /* Single character tokens (e.g. '{', ';' etc) */
                            return yytext[0];
		        }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 315 "lexer.l"
ECHO;
	YY_BREAK
#line 1429 "lexer.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 314 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 314 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 313);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 315 "lexer.l"


/*
PyObject*
integer_literal(const char* str, const int base)
{
   long value = strtoul(str, NULL, base);
   if(errno == ERANGE)
    {
	yywarning("Integer literal out of range");
    }

    return PyInt_FromLong(value);
}
*/

PyObject*
floating_point_literal(const char* str)
{
    double value = strtod(str, NULL);
    if(errno == ERANGE)
    {
	yywarning("Floating point literal out of range");
    }

    return PyFloat_FromDouble(value);
}

/***************************************************************/
/* end of lexer.l */
